site_name: oersted 
site_url: https://retkins.github.io/oersted
theme: terminal
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 1
            show_root_heading: false
            separate_signature: true
            show_signature_annotations: true

nav: 
  - "About oersted": index.md
  - "Tests and Validation": tests-and-validation.md
  - "Python API": python-api.md
  - "Rust API": "https://retkins.github.io/oersted/rust-api/oersted/index.html"