/*  Magnetic fields calculations

    All units are MKS: meters (m), amps (A), tesla (T)
*/

#include <math.h>
#include <stdlib.h>

#ifndef BIOTSAVART_H 
#define BIOTSAVART_H

// Physical constants
static const double PI = 3.141592654; 
static const double MU0 = 4*PI*1e-7; 
static const double MU04PI = 1e-7;

// --- 
// Analytical solutions 
// ---

// Calculate the magnetic field at the center of an ideal solenoid 
// B = mu0 * n * I, where n -> turns per unit length and I -> current
// 
// Note that the field is in the axial direction and is independent of radius, 
// though the solenoid must have L >> R for validity
// 
// Reference: eq 12.7.7 of: 
// https://phys.libretexts.org/Bookshelves/University_Physics/University_Physics_(OpenStax)/University_Physics_II_-_Thermodynamics_Electricity_and_Magnetism_(OpenStax)/12%3A_Sources_of_Magnetic_Fields/12.07%3A_Solenoids_and_Toroids
double bfield_ideal_solenoid(double turns_per_unit_length, double current);

// Calculate the magnetic field generated by a current loop of total current `I`, 
// radius `r` on a series of `n` points along its axis with position `z`. 
int bfield_loop_axis(
    const double *restrict z, size_t n, 
    const double I, const double R, 
    double *restrict Bz
);

// --- 
// Discrete integration solutions 
// ---

// Direct integration of the Biot Savart law for point sources on arbitrary obs pts
// B = mu0/4pi * vol * J x r' / |r'|^3
// 
// `cx, cy, cz` are the source point centroids, `vol` is their associated volume
// `Jx, Jy, Jz` are the current density vector components
int bfield_direct(
    const double *restrict cx, const double *restrict cy, const double *restrict cz, 
    const double *restrict vol, const double *restrict Jx, const double *restrict Jy, const double *restrict Jz, 
    size_t n_sources, // sources
    const double *restrict x, const double *restrict y, const double *restrict z, 
    size_t n_targets, // target pts
    double *restrict Bx, double *restrict By, double *restrict Bz, 
    int nthreads
);


// Explicit SIMD version of the above
int bfield_direct_simd(
    const double *restrict cx, const double *restrict cy, const double *restrict cz, 
    const double *restrict vol, const double *restrict Jx, const double *restrict Jy, const double *restrict Jz, 
    size_t n_sources,
    const double *restrict x, const double *restrict y, const double *restrict z, 
    size_t n_targets,
    double *restrict Bx, double *restrict By, double *restrict Bz, 
    int nthreads
);

// Direct integration of the Biot Savart law for point sources and self-fields
// B = mu0/4pi * vol * J x r' / |r'|^3
// (generally unused)
int bfield_direct_self(
    const double *restrict centx, const double *restrict centy, const double *restrict centz, 
    const double *restrict vol, const double *restrict Jx, const double *restrict Jy, const double *restrict Jz, 
    size_t n,
    double *restrict Bx, double *restrict By, double *restrict Bz, 
    int nthreads
);

// Integration of the Biot Savart law for point sources and self_fields using octree method
// B = mu0/4pi * vol * J x r' / |r'|^3
// 
// `phi` is the Barnes-Hut angle-opening criteria for accepting far-field points
//   values <= 0.1 are suggested
int bfield_octree(
    const double *restrict cx, const double *restrict cy, const double *restrict cz, 
    const double *restrict vol, const double *restrict Jx, const double *restrict Jy, const double *restrict Jz, 
    size_t n_sources, // sources
    const double *restrict x, const double *restrict y, const double *restrict z, 
    size_t n_targets, // obs pts
    double *restrict Bx, double *restrict By, double *restrict Bz, 
    int nthreads, 
    double phi
);

// Magnetic flux density generated by a series of finite-length wires
// (generally unused)
int bfield_wire(
    const double *restrict centx, const double *restrict centy, const double *restrict centz, 
    const double *restrict vol, 
    const double *restrict Jx, const double *restrict Jy, const double *restrict Jz, 
    size_t n_sources, 
    const double *restrict x, const double *restrict y, const double *restrict z, 
    double *restrict Bx, double *restrict By, double *restrict Bz, 
    size_t n_targets
);

#endif