/*  Magnetic fields calculations

    All units are MKS: meters (m), amps (A), tesla (T)
*/

#include <math.h>
#include <stdlib.h>

#ifndef BIOTSAVART_H 
#define BIOTSAVART_H

// Physical constants
static const double PI = 3.141592654; 
static const double MU0 = 4*PI*1e-7; 
static const double MU04PI = 1e-7;

// Calculate the magnetic field generated by a current loop of total current `I`, 
// radius `r` on a series of `n` points along its axis with position `z`. 
int bfield_loop_axis(
    const double *restrict z, size_t n, 
    const double I, const double R, 
    double *restrict Bz
);

// Direct integration of the Biot Savart law for point sources on arbitrary obs pts
// B = mu0/4pi * vol * J x r' / |r'|^3
// 
// `cx, cy, cz` are the source point centroids, `vol` is their associated volume
// `Jx, Jy, Jz` are the current density vector components
int bfield_direct(
    const double *restrict cx, const double *restrict cy, const double *restrict cz, 
    const double *restrict vol, const double *restrict Jx, const double *restrict Jy, const double *restrict Jz, 
    size_t n_sources, // sources
    const double *restrict x, const double *restrict y, const double *restrict z, 
    size_t n_targets, // target pts
    double *restrict Bx, double *restrict By, double *restrict Bz, 
    int nthreads
);

// Direct integration of the Biot Savart law for point sources and self-fields
// B = mu0/4pi * vol * J x r' / |r'|^3
// (generally unused)
int bfield_direct_self(
    const double *restrict centx, const double *restrict centy, const double *restrict centz, 
    const double *restrict vol, const double *restrict Jx, const double *restrict Jy, const double *restrict Jz, 
    size_t n,
    double *restrict Bx, double *restrict By, double *restrict Bz, 
    int nthreads
);

// Integration of the Biot Savart law for point sources and self_fields using octree method
// B = mu0/4pi * vol * J x r' / |r'|^3
// 
// `phi` is the Barnes-Hut angle-opening criteria for accepting far-field points
//   values <= 0.1 are suggested
int bfield_octree(
    const double *restrict cx, const double *restrict cy, const double *restrict cz, 
    const double *restrict vol, const double *restrict Jx, const double *restrict Jy, const double *restrict Jz, 
    size_t n_sources, // sources
    const double *restrict x, const double *restrict y, const double *restrict z, 
    size_t n_targets, // obs pts
    double *restrict Bx, double *restrict By, double *restrict Bz, 
    int nthreads, 
    double phi
);

// Magnetic flux density generated by a series of finite-length wires
// (generally unused)
int bfield_wire(
    const double *restrict centx, const double *restrict centy, const double *restrict centz, 
    const double *restrict vol, 
    const double *restrict Jx, const double *restrict Jy, const double *restrict Jz, 
    size_t n_sources, 
    const double *restrict x, const double *restrict y, const double *restrict z, 
    double *restrict Bx, double *restrict By, double *restrict Bz, 
    size_t n_targets
);

#endif