""" Magnetic field calculation routines
"""


from numpy import float64, ascontiguousarray, zeros, hstack, newaxis
from numpy.typing import NDArray

# Create bindings for calculation engine written in Rust
from ._thor import _bfield_direct, _bfield_octree

# For typing; currently unused
Nx3Arrray = NDArray[float64]


def bfield_direct(
    centroids: NDArray[float64], 
    vol: NDArray[float64], 
    jdensity: NDArray[float64], 
    targets: NDArray[float64], 
    nthreads: int=0
) -> NDArray[float64]: 
    """ Compute the magnetic field generated by a collection of current-carrying
        finite elements at `targets` using the direct summation Biot-Savart method.
    """ 

    ntargets = targets.shape[0]
    bx = zeros(ntargets)
    by = zeros(ntargets)
    bz = zeros(ntargets)

    _bfield_direct(
        ascontiguousarray(centroids[:,0]),
        ascontiguousarray(centroids[:,1]),
        ascontiguousarray(centroids[:,2]),
        ascontiguousarray(vol[:]),
        ascontiguousarray(jdensity[:,0]),
        ascontiguousarray(jdensity[:,1]),
        ascontiguousarray(jdensity[:,2]),
        ascontiguousarray(targets[:,0]),
        ascontiguousarray(targets[:,1]),
        ascontiguousarray(targets[:,2]),
        ascontiguousarray(bx[:]),
        ascontiguousarray(by[:]),
        ascontiguousarray(bz[:]), 
        nthreads
    )

    return hstack((bx[:, newaxis], by[:, newaxis], bz[:, newaxis]))


def bfield_octree(
    centroids: NDArray[float64], 
    vol: NDArray[float64], 
    jdensity: NDArray[float64], 
    targets: NDArray[float64], 
    theta: float=0.5, 
    leaf_threshold: int=1, 
    nthreads: int=0
) -> NDArray[float64]: 
    """ Compute the magnetic field generated by a collection of current-carrying
        finite elements at `targets` using the Barnes-Hut (octree) Biot-Savart method.

    Args
    ---
    theta: angle-opening parameter for Barnes-Hut; smaller values correspond to lower error
        at the expense of longer runtimes. Suggested values in the range of [0.01, 0.5]
    leaf_threshold: how many individual sources to aggregate per leaf

    """ 

    ntargets = targets.shape[0]
    bx = zeros(ntargets)
    by = zeros(ntargets)
    bz = zeros(ntargets)

    _bfield_octree(
        ascontiguousarray(centroids[:,0]),
        ascontiguousarray(centroids[:,1]),
        ascontiguousarray(centroids[:,2]),
        ascontiguousarray(vol[:]),
        ascontiguousarray(jdensity[:,0]),
        ascontiguousarray(jdensity[:,1]),
        ascontiguousarray(jdensity[:,2]),
        ascontiguousarray(targets[:,0]),
        ascontiguousarray(targets[:,1]),
        ascontiguousarray(targets[:,2]),
        ascontiguousarray(bx[:]),
        ascontiguousarray(by[:]),
        ascontiguousarray(bz[:]), 
        theta, 
        leaf_threshold, 
        nthreads
    )

    return hstack((bx[:, newaxis], by[:, newaxis], bz[:, newaxis]))