""" Magnetic field calculation routines
"""


from numpy import float64, ascontiguousarray, zeros, hstack, newaxis, array, pi
from numpy.typing import NDArray

# Create bindings for calculation engine written in Rust
from ._thor import _bfield_direct, _bfield_octree, _bfield_dualtree, _bfield_hexahedron

# For typing; currently unused
Nx3Arrray = NDArray[float64]


def bfield_direct(
    centroids: NDArray[float64], 
    vol: NDArray[float64], 
    jdensity: NDArray[float64], 
    targets: NDArray[float64], 
    nthreads: int=0
) -> NDArray[float64]: 
    """ Compute the magnetic field generated by a collection of current-carrying
        finite elements at `targets` using the direct summation Biot-Savart method.

    Args:
        centroids: [m] Nx3 array, location of source element centroids in 3D (cartesian) space
        vol: [m^3] N-length array, volume of each source element
        jdensity: [A/m^2] Nx3 array, current density vectors for each source element
        targets: [m] Nx3 array, describes location of target points at which to calculate magnetic fields
        nthreads: number of threads to use for the calculation (default: all available)

    Returns:
        [T] Nx3 array, magnetic flux density at each specified target point
    """ 

    ntargets = targets.shape[0]
    bx = zeros(ntargets)
    by = zeros(ntargets)
    bz = zeros(ntargets)

    _bfield_direct(
        ascontiguousarray(centroids[:,0]),
        ascontiguousarray(centroids[:,1]),
        ascontiguousarray(centroids[:,2]),
        ascontiguousarray(vol[:]),
        ascontiguousarray(jdensity[:,0]),
        ascontiguousarray(jdensity[:,1]),
        ascontiguousarray(jdensity[:,2]),
        ascontiguousarray(targets[:,0]),
        ascontiguousarray(targets[:,1]),
        ascontiguousarray(targets[:,2]),
        ascontiguousarray(bx[:]),
        ascontiguousarray(by[:]),
        ascontiguousarray(bz[:]), 
        nthreads
    )

    return hstack((bx[:, newaxis], by[:, newaxis], bz[:, newaxis]))


def bfield_octree(
    centroids: NDArray[float64], 
    vol: NDArray[float64], 
    jdensity: NDArray[float64], 
    targets: NDArray[float64], 
    theta: float=0.5, 
    leaf_threshold: int=16, 
    nthreads: int=0
) -> NDArray[float64]: 
    """ Compute the magnetic field generated by a collection of current-carrying
        finite elements at `targets` using the Barnes-Hut (octree) Biot-Savart method.

    Args:
        centroids: [m] Nx3 array, location of source element centroids in 3D (cartesian) space
        vol: [m^3] N-length array, volume of each source element
        jdensity: [A/m^2] Nx3 array, current density vectors for each source element
        targets: [m] Nx3 array, describes location of target points at which to calculate magnetic fields
        theta: angle-opening parameter for Barnes-Hut; smaller values correspond to lower error
            at the expense of longer runtimes. Suggested values in the range of [0.1, 0.5]
        leaf_threshold: how many individual sources to aggregate per leaf
        nthreads: number of threads to use for the calculation (default: all available)

    Returns:
        [T] Nx3 array, magnetic flux density at each specified target point

    """ 

    ntargets = targets.shape[0]
    bx = zeros(ntargets)
    by = zeros(ntargets)
    bz = zeros(ntargets)

    _bfield_octree(
        ascontiguousarray(centroids[:,0]),
        ascontiguousarray(centroids[:,1]),
        ascontiguousarray(centroids[:,2]),
        ascontiguousarray(vol[:]),
        ascontiguousarray(jdensity[:,0]),
        ascontiguousarray(jdensity[:,1]),
        ascontiguousarray(jdensity[:,2]),
        ascontiguousarray(targets[:,0]),
        ascontiguousarray(targets[:,1]),
        ascontiguousarray(targets[:,2]),
        ascontiguousarray(bx[:]),
        ascontiguousarray(by[:]),
        ascontiguousarray(bz[:]), 
        theta, 
        leaf_threshold, 
        nthreads
    )

    return (4*pi*10**-7)*hstack((bx[:, newaxis], by[:, newaxis], bz[:, newaxis]))

def bfield_dualtree(
    centroids: NDArray[float64], 
    vol: NDArray[float64], 
    jdensity: NDArray[float64], 
    targets: NDArray[float64], 
    theta_source: float=0.5, 
    theta_target: float=0.1,
    leaf_threshold: int=16, 
    nthreads: int=0
) -> NDArray[float64]: 
    """ Compute the magnetic field generated by a collection of current-carrying
        finite elements at `targets` using the dual Barnes-Hut (octree) Biot-Savart method.

    Args:
        centroids: [m] Nx3 array, location of source element centroids in 3D (cartesian) space
        vol: [m^3] N-length array, volume of each source element
        jdensity: [A/m^2] Nx3 array, current density vectors for each source element
        targets: [m] Nx3 array, describes location of target points at which to calculate magnetic fields
        theta_source, theta_target: angle-opening parameter for Barnes-Hut; smaller values correspond to lower error
            at the expense of longer runtimes. Suggested values in the range of [0.1, 0.5]
        leaf_threshold: how many individual sources to aggregate per leaf
        nthreads: number of threads to use for the calculation (default: all available)

    Returns:
        [T] Nx3 array, magnetic flux density at each specified target point

    """ 

    ntargets = targets.shape[0]
    bx = zeros(ntargets)
    by = zeros(ntargets)
    bz = zeros(ntargets)

    _bfield_dualtree(
        ascontiguousarray(centroids[:,0]),
        ascontiguousarray(centroids[:,1]),
        ascontiguousarray(centroids[:,2]),
        ascontiguousarray(vol[:]),
        ascontiguousarray(jdensity[:,0]),
        ascontiguousarray(jdensity[:,1]),
        ascontiguousarray(jdensity[:,2]),
        ascontiguousarray(targets[:,0]),
        ascontiguousarray(targets[:,1]),
        ascontiguousarray(targets[:,2]),
        ascontiguousarray(bx[:]),
        ascontiguousarray(by[:]),
        ascontiguousarray(bz[:]), 
        theta_source,
        theta_target, 
        leaf_threshold, 
        nthreads
    )

    return hstack((bx[:, newaxis], by[:, newaxis], bz[:, newaxis]))


def bfield_hexahedron(
    nodes: NDArray[float64], 
    jdensity: NDArray[float64], 
    target: NDArray[float64]
) -> NDArray[float64]: 
    
    nx = nodes[:,0] 
    ny = nodes[:,1] 
    nz = nodes[:,2] 

    b = _bfield_hexahedron(
        ascontiguousarray(nodes[:,0]), 
        ascontiguousarray(nodes[:,1]), 
        ascontiguousarray(nodes[:,2]), 
        ascontiguousarray(jdensity), 
        ascontiguousarray(target)
    )

    return array([b[0], b[1], b[2]])

