

use crate::vec3::Vec3;
use crate::sources::{edge_csys, edge_integral, transform};
use crate::math::distance;

/// Compute the magnetic flux density generated by an arbitrary tetrahedron in 3D space
/// 
/// # Arguments
/// - `x`: x coordinates of each corner node in 3D space
/// - `y`: y coordinates of each corner node in 3D space
/// - `z`: z coordinates of each corner node in 3D space
/// - `jdensity`: current density vector, assumed constant throughout the element 
/// 
/// # Returns 
///     magnetic flux density vector generated by the tetrahedron
/// 
/// # Reference  
/// 
/// CRYO-06-034: "MAGNUM - A Fortran Library for the Calculation of Magnetic Configurations"
/// https://supermagnet.sourceforge.io/notes/CRYO-06-034.pdf
/// 
pub fn hfield_tetrahedron(
    nx: &[f64],         // 4-length
    ny: &[f64],         // 4-length
    nz: &[f64],         // 4-length
    jdensity: &Vec3,   // 3-length
    target: &Vec3      // 3-length
) -> Vec3 {

    // Compute a total of 12 line integrals, along each edge (3 on each face)
    // Refer to the gmsh or ansys documentation for node numbering on a tet element: 
    // https://gmsh.info/doc/texinfo/gmsh.html#Node-ordering
    // https://ansyshelp.ansys.com/public/account/secured?returnurl=//////////Views/Secured/corp/v242/en/ans_elem/Hlp_E_SOLID236.html
    let node_map: [[[usize;3];3];4] = [
        [ [0,2,1], [2,1,0], [1,0,2] ],      // back face
        [ [0,3,2], [3,2,0], [2,0,3] ],      // left face 
        [ [1,2,3], [2,3,1], [3,1,2] ],      // right face
        [ [0,1,3], [1,3,0], [3,0,1] ],      // bottom face
    ];

    let mut s = [0.0; 3];
    // outer loop over faces 
    for i in 0..4 {
        let mut ni = [0.0; 3];      // normal on face 
        let mut s_face = 0.0; 

        for j in 0..3 {
            // Node numbers from the map 
            let n0 = node_map[i][j][0];
            let n1 = node_map[i][j][1];
            let n2 = node_map[i][j][2];

            // Local coordinate system tensor; transform the target point into the local system 
            let (xhat, yhat, zhat) = edge_csys(&[nx[n0], nx[n1], nx[n2]], &[ny[n0], ny[n1], ny[n2]], &[nz[n0], nz[n1], nz[n2]]);
            ni = zhat;
            let target_local = [target[0] - nx[n1], target[1] - ny[n1], target[2] - nz[n1]];
            let p = transform(&target_local, &xhat, &yhat, &zhat);
            let xppq2 = distance(&[nx[n1], ny[n1], nz[n1]], &[nx[n0], ny[n0], nz[n0]]);     // length of the edge, basically

            s_face += p[1] * (edge_integral(xppq2 - p[0], p[1], p[2]) - edge_integral(-p[0], p[1], p[2]));
        }
        s[0] += ni[0] * s_face;
        s[1] += ni[1] * s_face; 
        s[2] += ni[2] * s_face;
    }
    
    let inv_4pi = 1.0/(4.0*3.141592654);
    jdensity.cross(&Vec3(s)) * inv_4pi
}


fn tet_surface_integral(
    nodes: &[Vec3; 4], 
    target: &Vec3
) -> Vec3 {

    let mut s = Vec3([0.0; 3]);

    // Node mapping as previous
    let node_map: [[[usize;3];3];4] = [
        [ [0,2,1], [2,1,0], [1,0,2] ],      // back face
        [ [0,3,2], [3,2,0], [2,0,3] ],      // left face 
        [ [1,2,3], [2,3,1], [3,1,2] ],      // right face
        [ [0,1,3], [1,3,0], [3,0,1] ],      // bottom face
    ];

    // Outer loop over each face 
    for i in 0..4 {
        let mut ni = [0.0; 3];      // normal on face 
        let mut s_face = 0.0; 

        for j in 0..3 {
            // Node numbers from the map 
            let n0 = node_map[i][j][0];
            let n1 = node_map[i][j][1];
            let n2 = node_map[i][j][2];

            // Local coordinate system tensor; transform the target point into the local system 
            let (xhat, yhat, zhat) = edge_csys(&[nodes[n0][0], nodes[n1][0], nodes[n2][0]], &[nodes[n0][1], nodes[n1][1], nodes[n2][1]], &[nodes[n0][2], nodes[n1][2], nodes[n2][2]]);
            ni = zhat;
            let target_local = [target[0] - nodes[n1][0], target[1] - nodes[n1][1], target[2] - nodes[n1][2]];
            let p = transform(&target_local, &xhat, &yhat, &zhat);
            let xppq2 = distance(&nodes[n1].to_slice(), &nodes[n0].to_slice());     // length of the edge, basically

            s_face += p[1] * (edge_integral(xppq2 - p[0], p[1], p[2]) - edge_integral(-p[0], p[1], p[2]));
        }
        s[0] += ni[0] * s_face;
        s[1] += ni[1] * s_face; 
        s[2] += ni[2] * s_face;

    }
    s
}

/// Compute the h field generated by a magnetized tetrahedral element 
/// 
/// This converts the magnetization moment (m = M*V) into surface currents,
/// which are evaluated at the face of each element
pub fn hmag_tetrahedron(
    nodes: &[Vec3; 4], 
    magnetization: &Vec3,
    target: &Vec3
) -> Vec3 {

    let delta = 1e-4;
    let mut h = Vec3([0.0; 3]);

    for axis in 0..3 {
        let mut t_plus = *target;
        let mut t_minus = *target;
        t_plus[axis] += delta;
        t_minus[axis] -= delta;

        let s_plus = tet_surface_integral(nodes, &t_plus);
        let s_minus = tet_surface_integral(nodes, &t_minus);

        let ds = (s_plus - s_minus) * (0.5 / delta);
        h += ds * magnetization[axis];
    }

    let inv_4pi = 1.0 / (4.0 * std::f64::consts::PI);
    h * inv_4pi
}