

/// Octree sources
/// Represent monopole/dipole/quadrapole sources for a collection
/// of source points acting on a target point 
/// 

use crate::{
    MU0_4PI, 
    math::{cross, distance, mag3, dot3, unit_vector}, 
    vec3::Vec3
};
use std::f64::consts::PI;


/// H-field generated by a infinitesimal point current source
/// 
/// Handles singularities within the point element by providing it finite radius
pub fn h_point(centroid: &Vec3, vj: &Vec3, radius:  f64, target: &Vec3) -> Vec3 {
    let r: Vec3 = *target - *centroid;
    let mut vjr: Vec3 = (*vj).cross(&r);
    let rmag: f64 = r.mag();

    if rmag < radius {
        let inside_scale: f64 = (0.25/PI)*rmag*rmag*rmag/(radius*radius*radius); 
        vjr[0] *= inside_scale;
        vjr[1] *= inside_scale;
        vjr[2] *= inside_scale;
    }
    else {
        let inv_rmag3 = (0.25/PI) / (rmag*rmag*rmag);
        vjr[0] *= inv_rmag3;
        vjr[1] *= inv_rmag3;
        vjr[2] *= inv_rmag3;
    }

    return vjr;
}


/// H-field generated by an infinitesimal point dipole source 
/// 
/// For now, applies zero field to internal points. The use of this function should be limited
/// to self (zero) or adjacent elements in the mesh, not arbitrary points in the mesh domain.
/// TODO: Use the internal-sphere correction provided in ex 6.1 of griffith's:
/// https://peppyhare.github.io/griffiths-em/ch6-2/
/// and in Fitzpatrick:
/// https://farside.ph.utexas.edu/teaching/jk1/Electromagnetism/node61.html
pub fn h_point_dipole(centroid: &Vec3, moment: &Vec3, radius: f64, target: &Vec3) -> Vec3 {
    let r = *target - *centroid; 
    let rmag = r.mag();

    if rmag <= radius {
        // Internal magnetization field provided by the dipole moment at `radius`
        let m_field = *moment * (3.0/(4.0*PI*radius.powi(3))); 
        let h_field = m_field * (-1.0/3.0);
        return h_field;
    }
    
    // outside the sphere
    let rmag_inv = 1.0/rmag;
    let rhat = r * rmag_inv;

    let scale = (1.0/(4.0*PI)) * rmag_inv.powi(3);
    ((rhat * (3.0*rhat.dot(moment))) - *moment) * scale    
}


/// Monopole approximation of the effect of a group of source points
/// Approximates the group of sources as a single 'super source'
/// 
/// Returns: 
///     (monopole centroid, current density moment)
/// 
pub fn monopole(
    centroids: (&[f64], &[f64], &[f64]), 
    volumes: &[f64], 
    jdensity: (&[f64], &[f64], &[f64]), 
) -> ((f64, f64, f64), (f64, f64, f64)) {

    // TODO: length-check guards
    let n: usize = volumes.len();

    let mut mx = vec![0.0; n];
    let mut my = vec![0.0; n];
    let mut mz = vec![0.0; n];
    let mut mnet = vec![0.0; n]; 
    let (x, y, z) = centroids;
    let (jx, jy, jz) = jdensity;

    // Compute current density moments for each of the individual source points
    for i in 0..n { 
        mx[i] = volumes[i]*jx[i];
        my[i] = volumes[i]*jy[i];
        mz[i] = volumes[i]*jz[i];
        mnet[i] = (mx[i].powi(2) + my[i].powi(2) + mz[i].powi(2)).sqrt();
    }

    // Compute moment-weighted centroid location
    let mx_total: f64 = mx.iter().sum(); 
    let my_total: f64 = my.iter().sum(); 
    let mz_total: f64 = mz.iter().sum(); 

    let mnet_total: f64 = (mx_total*mx_total + my_total*my_total + mz_total*mz_total).sqrt();
    let mut cx = 0.0; 
    let mut cy = 0.0; 
    let mut cz = 0.0; 

    for i in 0..n {
        cx += x[i]*mnet[i]; 
        cy += y[i]*mnet[i]; 
        cz += z[i]*mnet[i];
    }
    cx /= mnet_total; 
    cy /= mnet_total; 
    cz /= mnet_total;

    (
        (cx, cy, cz), 
        (mx_total, my_total, mz_total)
    )
}


/// Computes the magnetic dipole of a collection of source points in 3D space
/// 
/// $$ m = 1/2 \cdot \int\int\int{r' \times j(r') dV} $$
pub fn dipole(
    centroids: (&[f64], &[f64], &[f64]), 
    volumes: &[f64], 
    jdensity: (&[f64], &[f64], &[f64])
) -> (f64, f64, f64) 
{
    let n: usize = centroids.0.len();
    // The monopole calculation provides the centroid of the source point distribution
    let ((cx, cy, cz), _) = monopole(centroids, volumes, jdensity);

    let mut moment: (f64, f64, f64) = (0.0, 0.0, 0.0);
    let mut rxj = [0.0; 3];

    // Compute the position vector 
    for i in 0..n {
        let rpx: f64 = centroids.0[i] - cx; 
        let rpy: f64 = centroids.1[i] - cy; 
        let rpz: f64 = centroids.2[i] - cz; 
        let jx: f64 = jdensity.0[i]; 
        let jy: f64 = jdensity.1[i]; 
        let jz: f64 = jdensity.2[i]; 
        cross(&[rpx, rpy, rpz], &[jx, jy, jz], &mut rxj); 
        moment.0 += rxj[0]; 
        moment.1 += rxj[1]; 
        moment.2 += rxj[2];
    }
    moment.0 *= 0.5; 
    moment.1 *= 0.5; 
    moment.2 *= 0.5;

    return moment;
}


// Compute the edge integral for a finite element source 
// 
// Includes a small finite value to prevent singularities when the target is close to the edge
//
// Reference: Eq 52 of CRYO-06-034
fn edge_integral(x: f64, y: f64, z: f64) -> f64 {
    let r: f64 = mag3(x, y, z);
    (x + r).ln()
    + z.abs()/(y+1e-8)
    * ((x*z.abs()/(y*r+1e-8)).atan() - (x/(y+1e-8)).atan())
}


// Compute the unit vectors of an edge csys given 3 nodes
// Nodes should be in right hand rule order
// middle node is the 'anchor', xhat points from node 1 to node 0
// yhat points away from the center of the face 
fn edge_csys(
    x: &[f64; 3], 
    y: &[f64; 3], 
    z: &[f64; 3]
) -> ([f64; 3], [f64; 3], [f64; 3]) {

    // first edge defines x'-axis 
    let xp_hat = unit_vector(&[x[1], y[1], z[1]], &[x[0], y[0], z[0]]);

    // second edge defines the next in plane direction to find the out of plane z
    // it is not returned because it is not guaranteed to be orthogonal to x and z
    let yp_hat_temp = unit_vector(&[x[2], y[2], z[2]], &[x[1], y[1], z[1]]); 

    // unit vector normal to surface 
    let mut zp_hat = [0.0; 3];
    cross(&xp_hat, &yp_hat_temp, &mut zp_hat);
    let norm = mag3(zp_hat[0], zp_hat[1], zp_hat[2]);
    zp_hat[0] /= norm; 
    zp_hat[1] /= norm; 
    zp_hat[2] /= norm;

    // other in-plane direction, not necessarily aligned with an edge
    let mut yp_hat = [0.0; 3]; 
    cross(&xp_hat, &zp_hat, &mut yp_hat); 
    return (xp_hat, yp_hat, zp_hat)
}


// transform a global xyz position into a local coordinate system
fn transform(g: &[f64; 3], xhat: &[f64; 3], yhat: &[f64; 3], zhat: &[f64; 3]) -> [f64; 3] {
    [dot3(xhat, g), dot3(yhat, g), dot3(zhat, g)]
}


/// Compute the magnetic flux density generated by an arbitrary hexahedron in 3D space
/// 
/// # Arguments
/// - `x`: x coordinates of each corner node in 3D space
/// - `y`: y coordinates of each corner node in 3D space
/// - `z`: z coordinates of each corner node in 3D space
/// - `jdensity`: current density vector, assumed constant throughout the element 
/// 
/// # Returns 
///     magnetic flux density vector generated by the hexahedron
/// 
/// # Reference  
/// 
/// CRYO-06-034: "MAGNUM - A Fortran Library for the Calculation of Magnetic Configurations"
/// https://supermagnet.sourceforge.io/notes/CRYO-06-034.pdf
/// 
pub fn bfield_hexahedron(
    nx: &[f64],         // 8-length
    ny: &[f64],         // 8-length
    nz: &[f64],         // 8-length
    jdensity: &[f64],   // 3-length
    target: &[f64]      // 3-length
) -> [f64; 3] {

    // Compute a total of 24 line integrals, along each edge (4 on each face)
    // Refer to the gmsh or ansys documentation for node numbering on a hex element: 
    // https://gmsh.info/doc/texinfo/gmsh.html#Node-ordering
    // https://ansyshelp.ansys.com/public/account/secured?returnurl=//////////Views/Secured/corp/v242/en/ans_elem/Hlp_E_SOLID236.html
    let node_map: [[[usize;3];4];6] = [
        [ [0,3,2], [3,2,1], [2,1,0], [1,0,3]],      // bottom face  
        [ [4,5,6], [5,6,7], [6,7,4], [7,4,5]],      // top face 
        [ [0,4,7], [4,7,3], [7,3,0], [3,0,4]],      // left face
        [ [1,2,6], [2,6,5], [6,5,1], [5,1,2]],      // right face
        [ [0,1,5], [1,5,4], [5,4,0], [4,0,1]],      // front face 
        [ [2,3,7], [3,7,6], [7,6,2], [6,2,3]]       // back face
    ];

    let mut s = [0.0; 3];
    // outer loop over faces 
    for i in 0..6 {
        let mut ni = [0.0; 3];      // normal on face 
        let mut s_face = 0.0; 

        for j in 0..4 {
            // Node numbers from the map 
            let n0 = node_map[i][j][0];
            let n1 = node_map[i][j][1];
            let n2 = node_map[i][j][2];

            // Local coordinate system tensor; transform the target point into the local system 
            let (xhat, yhat, zhat) = edge_csys(&[nx[n0], nx[n1], nx[n2]], &[ny[n0], ny[n1], ny[n2]], &[nz[n0], nz[n1], nz[n2]]);
            ni = zhat;
            let target_local = [target[0] - nx[n1], target[1] - ny[n1], target[2] - nz[n1]];
            let p = transform(&target_local, &xhat, &yhat, &zhat);
            let xppq2 = distance(&[nx[n1], ny[n1], nz[n1]], &[nx[n0], ny[n0], nz[n0]]);     // length of the edge, basically

            s_face += p[1] * (edge_integral(xppq2 - p[0], p[1], p[2]) - edge_integral(-p[0], p[1], p[2]));
        }
        s[0] += ni[0] * s_face;
        s[1] += ni[1] * s_face; 
        s[2] += ni[2] * s_face;
    }
    
    let mut b = [0.0; 3]; 
    cross(&[jdensity[0], jdensity[1], jdensity[2]], &s, &mut b); 

    [MU0_4PI*b[0], MU0_4PI*b[1], MU0_4PI*b[2]]
}

#[cfg(test)]
mod tests {

    use super::*;

    #[test] 
    fn test_monopole() {
        // if the sources are in the same position, this should be a
        // simple sum 
        let n: usize = 5;
        let cx = vec![1.0; n];
        let cy = vec![2.0; n];
        let cz = vec![3.0; n];
        let volumes = vec![1e-3; n];
        let jx = vec![1e8; n];
        let jy = vec![0.0; n];
        let jz = vec![0.0; n];
        let ((x, y, z), (mx, my, mz)) = monopole((&cx, &cy, &cz), &volumes, (&jx, &jy, &jz));

        assert_eq!(x, cx[0]); 
        assert_eq!(y, cy[0]); 
        assert_eq!(z, cz[0]); 
        let mx_expected: f64 = jx.iter().zip(volumes).map(|(_jx, _v)| _jx*_v).sum();
        assert_eq!(mx_expected, mx);
        assert_eq!(0.0, my);
        assert_eq!(0.0, mz);
    }

    #[test]
    fn test_dipole() {
        let cx = [1.0, 0.0, 2.0, -1.0]; 
        let cy = [-1.0, 2.0, 0.0, 1.0]; 
        let cz = [0.0, 0.0, 0.0, 0.0];
        let jx = [0.0, 0.0, 0.0, 0.0]; 
        let jy = [1e7, 1e7, 1e7, 1e7]; 
        let jz = [0.0, 0.0, 0.0, 0.0]; 

        let volumes = [1e-4, 1e-4, 1e-4, 1e-4]; 
        let (_, mm) = monopole((&cx, &cy, &cz), &volumes, (&jx, &jy, &jz));
        let dm = dipole((&cx, &cy, &cz), &volumes, (&jx, &jy, &jz));


        println!("Monopole = ({:.6}, {:.6}, {:.6})", mm.0, mm.1, mm.2);
        println!("Dipole   = ({:.6}, {:.6}, {:.6})", dm.0, dm.1, dm.2);
    }

    #[test]
    fn test_hex() {
        // unit cube with origin at center
        let nx = [0.5, 0.5, -0.5, -0.5, 0.5, 0.5, -0.5, -0.5]; 
        let ny = [-0.5, 0.5, 0.5, -0.5, -0.5, 0.5, 0.5, -0.5];
        let nz = [-0.5, -0.5, -0.5, -0.5, 0.5, 0.5, 0.5, 0.5];

        let target = [0.5, 0.55, -0.55]; 
        let jdensity = [0.0, 1000.0e5, 0.0];

        let b_hex = bfield_hexahedron(&nx, &ny, &nz, &jdensity, &target);
        let mut jxr = [0.0; 3]; 
        cross(&jdensity, &target, &mut jxr);
        let multiplier = MU0_4PI * 1.0 / distance(&target, &[0.0; 3]).powi(3);
        let b_point = [multiplier*jxr[0], multiplier*jxr[1], multiplier*jxr[2]]; 

        println!("Point: {:?}", b_point); 
        println!("Hex:   {:?}", b_hex);
    }

}